/**
 * Cross-compilation toolchain emission: per-triple CMake toolchain files, an
 * env.sh for everything else, and per-arch clang wrapper scripts.
 *
 * Deliberately unopinionated: only the settings strictly required to retarget
 * a host clang at the SDK are emitted, and everything in the CMake files uses
 * `*_INIT` variables so projects that manage their own flags keep control.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { VERSION, XmacError } from "./util";

/** Wrappers and toolchain files are always generated for every supported arch. */
export const ALL_ARCHS = ["arm64", "x86_64"] as const;

export function normalizeArch(a: string): string {
  const k = a.trim().toLowerCase();
  if (k === "aarch64") return "arm64";
  if (k === "amd64") return "x86_64";
  if (k !== "arm64" && k !== "x86_64")
    throw new XmacError(`unsupported --arch '${a}' (use arm64 and/or x86_64)`);
  return k;
}

/** The CMake toolchain file body for a given set of architectures. */
function cmakeToolchain(filePath: string, sdkRel: string, archs: string[], minOs: string): string {
  return `# Generated by xmac ${VERSION} — cross-compile to ${archs.join("/")} macOS from Linux.
#
#   cmake -B build -G Ninja --toolchain ${filePath}
#
# Requirements on the build host: clang and lld (for ld64.lld). Any
# clang >= 13 works; 15+ recommended. Override the compiler with
# -DXMAC_CLANG=/path/to/clang if the default is not what you want.

set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR ${archs[0]})

get_filename_component(_xmac_root "\${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
set(XMAC_SDK "\${_xmac_root}/${sdkRel}" CACHE PATH "macOS SDK root")

set(CMAKE_OSX_SYSROOT "\${XMAC_SDK}" CACHE PATH "" FORCE)
set(CMAKE_OSX_ARCHITECTURES "${archs.join(";")}" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "${minOs}" CACHE STRING "" FORCE)
set(CMAKE_MACOSX_RPATH ON)

# Locate clang/lld. Prefer an explicit override, then PATH.
if(NOT XMAC_CLANG)
  find_program(XMAC_CLANG NAMES clang REQUIRED)
endif()
get_filename_component(_xmac_clang_dir "\${XMAC_CLANG}" DIRECTORY)
if(NOT XMAC_CLANGXX)
  find_program(XMAC_CLANGXX NAMES clang++ HINTS "\${_xmac_clang_dir}" REQUIRED)
endif()
if(NOT XMAC_LLD)
  find_program(XMAC_LLD NAMES ld64.lld HINTS "\${_xmac_clang_dir}")
endif()
if(NOT XMAC_LLD)
  message(FATAL_ERROR "xmac: ld64.lld not found — install lld (apt-get install lld / brew install llvm)")
endif()

set(CMAKE_C_COMPILER   "\${XMAC_CLANG}")
set(CMAKE_CXX_COMPILER "\${XMAC_CLANGXX}")
set(CMAKE_OBJC_COMPILER  "\${XMAC_CLANG}")
set(CMAKE_OBJCXX_COMPILER "\${XMAC_CLANGXX}")
set(CMAKE_ASM_COMPILER "\${XMAC_CLANG}")

# A non-Apple clang defaults to the *build host's* triple; -arch alone is not
# enough to retarget it. CMake appends --target=<this> to every compile.
foreach(_lang C CXX OBJC OBJCXX ASM)
  set(CMAKE_\${_lang}_COMPILER_TARGET "${archs[0]}-apple-macosx${minOs}")
endforeach()

# Use LLVM binutils when available so ranlib/ar understand Mach-O + fat files.
find_program(XMAC_AR NAMES llvm-ar HINTS "\${_xmac_clang_dir}")
find_program(XMAC_RANLIB NAMES llvm-ranlib HINTS "\${_xmac_clang_dir}")
find_program(XMAC_LIPO NAMES llvm-lipo HINTS "\${_xmac_clang_dir}")
find_program(XMAC_NM NAMES llvm-nm HINTS "\${_xmac_clang_dir}")
find_program(XMAC_STRIP NAMES llvm-strip HINTS "\${_xmac_clang_dir}")
find_program(XMAC_INSTALL_NAME_TOOL NAMES llvm-install-name-tool HINTS "\${_xmac_clang_dir}")
foreach(_t AR RANLIB NM STRIP)
  if(XMAC_\${_t})
    set(CMAKE_\${_t} "\${XMAC_\${_t}}" CACHE FILEPATH "" FORCE)
  endif()
endforeach()
if(XMAC_INSTALL_NAME_TOOL)
  set(CMAKE_INSTALL_NAME_TOOL "\${XMAC_INSTALL_NAME_TOOL}" CACHE FILEPATH "" FORCE)
endif()

# clang's Darwin driver invokes a system linker. Ask for the lld *flavor*
# (so the driver emits modern -platform_version arguments rather than the
# legacy flags ld64.lld no longer accepts) and add the directory containing
# ld64.lld as a program-search prefix so it is found even when it does not
# sit next to clang.
get_filename_component(_xmac_lld_dir "\${XMAC_LLD}" DIRECTORY)
# Plain set() rather than append: toolchain files are included several times
# per configure and appends would accumulate duplicates.
set(CMAKE_EXE_LINKER_FLAGS_INIT    "-fuse-ld=lld -B\${_xmac_lld_dir}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld -B\${_xmac_lld_dir}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld -B\${_xmac_lld_dir}")

# Use the SDK's libc++ headers, not the host clang's own copy (which targets
# the build machine and lacks a usable __config_site for Darwin). These are
# *_INIT variables: the project and the user can still append or override.
set(CMAKE_CXX_FLAGS_INIT    "-stdlib++-isystem \${XMAC_SDK}/usr/include/c++/v1")
set(CMAKE_OBJCXX_FLAGS_INIT "-stdlib++-isystem \${XMAC_SDK}/usr/include/c++/v1")

# Search only the SDK, never the build host's headers/libraries.
set(CMAKE_FIND_ROOT_PATH "\${XMAC_SDK}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_FRAMEWORK_PATH "\${XMAC_SDK}/System/Library/Frameworks")
`;
}

export function emitToolchain(
  outDir: string,
  sdkName: string,
  archs: string[],
  minOs: string,
): { cmake: string; cmakeAll: string[]; env: string; wrappers: string[] } {
  const sdkRel = `SDKs/${sdkName}`;
  const binDir = path.join(outDir, "bin");
  fs.mkdirSync(binDir, { recursive: true });

  // --- CMake toolchains ----------------------------------------------------
  // One file per target triple (matching the bin/<triple>-cc wrappers), plus
  // a universal one when more than one arch was requested. The summary points
  // at whichever matches --arch.
  const cmakeAll: string[] = [];
  const writeCmake = (fileName: string, fileArchs: string[]) => {
    const p = path.join(outDir, fileName);
    fs.writeFileSync(p, cmakeToolchain(p, sdkRel, fileArchs, minOs));
    cmakeAll.push(p);
    return p;
  };
  let cmakePath = "";
  for (const arch of ALL_ARCHS) {
    const p = writeCmake(`${arch}-apple-darwin.toolchain.cmake`, [arch]);
    if (archs[0] === arch) cmakePath = p;
  }
  if (archs.length > 1) cmakePath = writeCmake("universal-apple-darwin.toolchain.cmake", archs);

  // --- env.sh for ninja / make / cargo / meson -----------------------------
  const primaryArch = archs[0];
  const archFlags = archs.map((a) => `-arch ${a}`).join(" ");
  const envPath = path.join(outDir, "env.sh");
  const env = `# Generated by xmac ${VERSION} — source this for non-CMake builds.
#
#   source ${envPath}
#   $CC -o hello hello.c
#
# Works with make, ninja (via CC/CXX in your generator), autotools
# (./configure --host=${primaryArch}-apple-darwin), cargo (see below), etc.

_xmac_root="$(cd "$(dirname "\${BASH_SOURCE[0]:-$0}")" && pwd)"
export SDKROOT="$_xmac_root/${sdkRel}"
export MACOSX_DEPLOYMENT_TARGET="${minOs}"

_xmac_lld="$(command -v ld64.lld || true)"
if [ -z "$_xmac_lld" ]; then
  echo "xmac: warning: ld64.lld not found on PATH; linking will fail (install lld)" >&2
fi

export XMAC_CFLAGS="--sysroot=$SDKROOT ${archFlags} -mmacosx-version-min=${minOs}"
export XMAC_CXXFLAGS="$XMAC_CFLAGS -stdlib++-isystem $SDKROOT/usr/include/c++/v1"
export XMAC_LDFLAGS="-fuse-ld=lld -B$(dirname "\${_xmac_lld:-/usr/bin/ld64.lld}") -Wl,-syslibroot,$SDKROOT"

export CC="$_xmac_root/bin/${primaryArch}-apple-darwin-cc"
export CXX="$_xmac_root/bin/${primaryArch}-apple-darwin-c++"
export AR="$(command -v llvm-ar || command -v ar)"
export RANLIB="$(command -v llvm-ranlib || command -v ranlib)"

# Cargo / Rust convenience (requires \`rustup target add <triple>-apple-darwin\`):
${archs
  .map((a) => {
    const rustArch = a === "arm64" ? "aarch64" : a;
    const envArch = rustArch.toUpperCase();
    return `export CARGO_TARGET_${envArch}_APPLE_DARWIN_LINKER="$_xmac_root/bin/${a}-apple-darwin-cc"
export CC_${rustArch}_apple_darwin="$_xmac_root/bin/${a}-apple-darwin-cc"
export CXX_${rustArch}_apple_darwin="$_xmac_root/bin/${a}-apple-darwin-c++"`;
  })
  .join("\n")}
`;
  fs.writeFileSync(envPath, env);

  // --- compiler wrapper scripts -------------------------------------------
  // Emit wrappers for every arch regardless of --arch; they cost nothing and
  // make it trivial to build the "other" slice of a universal binary.
  const wrappers: string[] = [];
  for (const arch of ALL_ARCHS) {
    for (const [tool, driver] of [
      ["cc", "clang"],
      ["c++", "clang++"],
    ] as const) {
      const isCxx = tool === "c++";
      const wrapper = `#!/bin/sh
# Generated by xmac ${VERSION}. Cross-compile ${isCxx ? "C++/ObjC++" : "C/ObjC"} to ${arch}-apple-macosx.
here="$(cd "$(dirname "$0")/.." && pwd)"
sdk="$here/${sdkRel}"
lld="\${XMAC_LLD:-$(command -v ld64.lld)}"
if [ -z "$lld" ]; then
  echo "xmac: ld64.lld not found on PATH (install lld)" >&2
  exit 1
fi
exec "\${XMAC_${driver === "clang" ? "CLANG" : "CLANGXX"}:-${driver}}" \\
  --target=${arch}-apple-macosx\${MACOSX_DEPLOYMENT_TARGET:-${minOs}} \\
  -isysroot "$sdk" \\
  -fuse-ld=lld \\
  -B "$(dirname "$lld")" \\
  -Wl,-syslibroot,"$sdk" \\${
    isCxx
      ? `
  -stdlib++-isystem "$sdk/usr/include/c++/v1" \\`
      : ""
  }
  "$@"
`;
      const p = path.join(binDir, `${arch}-apple-darwin-${tool}`);
      fs.writeFileSync(p, wrapper);
      fs.chmodSync(p, 0o755);
      wrappers.push(p);
    }
  }
  return { cmake: cmakePath, cmakeAll, env: envPath, wrappers };
}
